- name: payment
  hosts: payment
  become: yes
  tasks:
  - name: Install python packages
    ansible.builtin.dnf:
      name: "{{item}}" 
      state: present
    loop:
    - python36
    - gcc
    - python3-devel
 
  - name: create roboshop user
    ansible.builtin.user:
     name: roboshop

  - name: recruivesely remove directory
    ansible.builtin.file:
     path: /app
     state: absent

  - name: create directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: download payments service
    ansible.builtin.get_url:
      url: curl -L -o /tmp/payment.zip https://roboshop-builds.s3.amazonaws.com/payment.zip

  - name: extract payments.zip
    ansible.builtin.unarchieve:
      src: /app
      dest: /tmp/payment.zip

  - name: install pipeline
    ansible.builtin.command: pip3.6 install -r requirements.txt

  - name: copy payment.service
    ansible.built.copy:
     src: payment.service
     dest:  /etc/systemd/system/payment.service    
  
  - name: deamon realod and start
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable payment
    ansible.builtin.service:
      name: payment
      state: restarted
      enabled: yes
       