-name: redis component
 hosts: redis
 become : yes
 taks:
 - name: install remis
   anisble.builtin.dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm 
    state: yes
    disable_gpg_check: true

 - name: enable redis
   ansible.builtin.dnf:  dnf module enable redis:remi-6.2 

 - name: install redis
   ansible.builtin.dnf:
    name: redis
    state: yes

 - name: allow remote connection  
   anisble.builtin.replace:
    path: /etc/redis.conf
     regexp: '127.0.0.1'
     replace: '0.0.0.0'

 - name: enable and start redis
    ansible.builtin.service:
     name: redis
      state: restarted
      enabled: ye   